//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "click")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub click_id: i32,
    pub date: Option<String>,
    pub level_id: Option<i32>,
    pub count_today: Option<i32>,
    pub fake_count: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
