//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "systeminfo")]
pub struct Model {
    pub level_id: Option<i32>,
    pub info_type: Option<String>,
    pub my_int: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub my_str: Option<String>,
    pub my_bigint: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
