//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "click")]
pub struct Model {
    #[sea_orm(column_name = "Click_id", primary_key, auto_increment = false)]
    pub click_id: i32,
    #[sea_orm(column_name = "Date", column_type = "Text", nullable)]
    pub date: Option<String>,
    #[sea_orm(column_name = "Level_id")]
    pub level_id: Option<i32>,
    #[sea_orm(column_name = "Attempt_times")]
    pub attempt_times: Option<i32>,
    #[sea_orm(column_name = "Pass_times")]
    pub pass_times: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
